version: "3"
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306

  node:
    build: ./node
    image: cooler2020/node-web-app
    depends_on:
      - db
    tty: true
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    image: cooler2020/nginx-web-app
    ports:
      - "8080:80"
    depends_on:
      - node